#!/usr/bin/python

import sys
import os
import argparse
from libstu import *

THIS = os.path.basename(sys.argv[0])
DEFAULT_INPUT = THIS + "-input"

def main():
    arg_parser = argparse.ArgumentParser(prog=THIS)
    arg_parser.add_argument("-f", "--file", default=DEFAULT_INPUT,
                            help="specify the input file (default: %(default)s)", metavar="file")
    args = arg_parser.parse_args()

    # Open input file

    input_path = os.path.abspath(args.file)
    if not os.path.exists(input_path):
        print("%s: Error: File '%s' not found" % (THIS, args.file))
        return 1

    input = open(input_path, "r")
    if input is None:
        print("%s: Error: Couldn't open file '%s'" % (THIS, input_path))
        return 1

    # Main loop
    frequency = 0
    final_frequency = None
    frequencies = { 0: 1 }
    first_twice = None
    changes = []

    for line in input:
        changes.append(int(line))
        frequency += changes[-1]
        if first_twice is None:
            if frequency not in frequencies:
                frequencies[frequency] = 1
            else:
                first_twice = frequency

    final_frequency = frequency

    if first_twice is None:
        len_changes = len(changes)
        i = 0
        while True:
            frequency += changes[i]
            if frequency not in frequencies:
                frequencies[frequency] = 1
            else:
                first_twice = frequency
                break
            i += 1
            i %= len_changes
        

    print("final_frequency is %s" % final_frequency)
    print("first_twice is %s" % first_twice)

    return 0


if __name__ == "__main__":
    sys.exit(main())
