#!/usr/bin/python

import sys
import os
import argparse
from libstu import *

THIS = os.path.basename(sys.argv[0])
DEFAULT_INPUT = THIS + "-input"

def main():
    arg_parser = argparse.ArgumentParser(prog=THIS)
    arg_parser.add_argument("-f", "--file", default=DEFAULT_INPUT,
                            help="specify the input file (default: %(default)s)", metavar="file")
    args = arg_parser.parse_args()

    # Open input file

    input_path = os.path.abspath(args.file)
    if not os.path.exists(input_path):
        print("%s: Error: File '%s' not found" % (THIS, args.file))
        return 1

    input = open(input_path, "r")
    if input is None:
        print("%s: Error: Couldn't open file '%s'" % (THIS, input_path))
        return 1

    # Main loop

    X = 0
    Y = 1

    coords = []
    top_left = []
    bottom_right = []

    coord = map(int, input.readline().strip().split(','))
    coords.append(coord)
    top_left = list(coord)
    bottom_right = list(coord)
    for line in input:
        coord = map(int, line.strip().split(','))
        coords.append(coord)
        if coord[X] < top_left[X]:
            top_left[X] = coord[X]
        elif coord[X] > bottom_right[X]:
            bottom_right[X] = coord[X]
        if coord[Y] < top_left[Y]:
            top_left[Y] = coord[Y]
        elif coord[Y] > bottom_right[Y]:
            bottom_right[Y] = coord[Y]
    print coords

    # Loop over coords
    num_coords = len(coords)
    while True:
        pass

    return 0


if __name__ == "__main__":
    sys.exit(main())
