#!/usr/bin/python

import sys
import os
import argparse
from libstu import *
from computer import *
import itertools

THIS = os.path.basename(sys.argv[0])
DEFAULT_INPUT = THIS + "-input"

class amplifier:
    def __init__(self, program):
        self.computer = computer(program)
        self.signal = 0

    def __iter__(self):
        return self

    def __next__(self):
        return self.signal

def main():
    arg_parser = argparse.ArgumentParser(prog=THIS)
    arg_parser.add_argument("-f", "--file", default=DEFAULT_INPUT,
                            help="specify the input file (default: %(default)s)", metavar="file")
    args = arg_parser.parse_args()

    # Open input file

    input_path = os.path.abspath(args.file)
    if not os.path.exists(input_path):
        print("%s: Error: File '%s' not found" % (THIS, args.file))
        return 1

    input = open(input_path, "r")
    if input is None:
        print("%s: Error: Couldn't open file '%s'" % (THIS, input_path))
        return 1

    # Main loop
    program = [ int(x) for x in input.readline().rstrip().split(',') ]
    amps = [ computer(program), computer(program), computer(program),
             computer(program), computer(program) ]

    max_signal = [ 0, [] ]
    for phase_perm in itertools.permutations([5,6,7,8,9]):
        print("-= perm %s" % (phase_perm,))
        # signal must be mutable so it can be changed by the receive function
        signal = [ 0 ]
        # First pass, they all get the phase numbers
        def phase_input_generator():
            for phase in phase_perm:
                yield phase
                yield signal[0]
            while True:
                yield signal[0]
        gen = phase_input_generator()
        def provide_input():
            return next(gen)
        def receive_output(val):
            signal[0] = val
        # Initialization pass
        for i in range(0, 5):
            amps[i].poke_input = provide_input
            amps[i].peek_output = receive_output
            amps[i].reset()
        # Rest of the passes, continue until halted
        i = 0
        last_from_amp_e = 0
        while True:
            print("-= %d: signal %d" % (i, signal[0]))
            amps[i].run()
            for j in range(0, 5):
                print("-= [ %d is %d ]" % (j, amps[j].state))
            if amps[i].state == computer.STATE_HALTED:
                # save last amp e output
                if last_from_amp_e > max_signal[0]:
                    max_signal[0] = last_from_amp_e
                    max_signal[1] = phase_perm
                break
            if i == 4:
                last_from_amp_e = signal[0]
            i = (i + 1) % len(amps)
        print("-= signal %d  max %d perm %s" % (signal[0], max_signal[0], max_signal[1]))

    return 0


if __name__ == "__main__":
    sys.exit(main())
