#!/usr/bin/python3

import sys
import os
import argparse
from libstu import *

THIS = os.path.basename(sys.argv[0])
DEFAULT_INPUT = THIS + "-input"

def main():
    arg_parser = argparse.ArgumentParser(prog=THIS)
    arg_parser.add_argument("-f", "--file", default=DEFAULT_INPUT,
                            help="specify the input file (default: %(default)s)", metavar="file")
    args = arg_parser.parse_args()

    # Open input file

    input_path = os.path.abspath(args.file)
    if not os.path.exists(input_path):
        print("%s: Error: File '%s' not found" % (THIS, args.file))
        return 1

    input = open(input_path, "r")
    if input is None:
        print("%s: Error: Couldn't open file '%s'" % (THIS, input_path))
        return 1

    # Main loop

    # B = 1
    # F = 0
    # R = 1
    # L = 0
    max_seat = { 'seatid': 0 }
    all_seats = list(range(0, 128 * 8))
    for line in input:
        line = line.strip()
        row = int(line[:7].replace('B', '1').replace('F', '0'), base=2)
        col = int(line[7:].replace('R', '1').replace('L', '0'), base=2)
        seatid = row * 8 + col
        print(f'{line}: row {row}, column {col}, seat id {seatid}')
        if seatid > max_seat['seatid']:
            max_seat['seatid'] = seatid
            max_seat['line'] = line
            max_seat['row'] = row
            max_seat['col'] = col
        all_seats.remove(seatid)
    print(f"{max_seat['line']}: row {max_seat['row']}, column {max_seat['col']}, seat id {max_seat['seatid']} MAX")
    my_seat = all_seats[all_seats.index(max_seat['seatid'] + 1) - 1]
    print(f'My seat ID: {my_seat}')

    return 0


if __name__ == "__main__":
    sys.exit(main())
